site_title = "Karlçš„arXivDaily"
limit_days = 15
cache_url = "https://arxiv.karltan.com/cache.json"

# 40 items
[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

# [[sources]]
# limit = 150
# category = "cs.CL"
# title = "Computation and Language"

# [[sources]]
# limit = 150
# category = "cs.CC"
# title = "Computational Complexity"

# [[sources]]
# limit = 150
# category = "cs.CE"
# title = "Computational Engineering, Finance, and Science"

[[sources]]
limit = 150
category = "cs.CG"
title = "Computational Geometry"

[[sources]]
limit = 150
category = "cs.GT"
title = "Computer Science and Game Theory"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

# [[sources]]
# limit = 150
# category = "cs.CY"
# title = "Computers and Society"

# [[sources]]
# limit = 150
# category = "cs.CR"
# title = "Cryptography and Security"

# [[sources]]
# limit = 150
# category = "cs.DS"
# title = "Data Structures and Algorithms"

# [[sources]]
# limit = 150
# category = "cs.DB"
# title = "Databases"

# [[sources]]
# limit = 150
# category = "cs.DL"
# title = "Digital Libraries"

# [[sources]]
# limit = 150
# category = "cs.DM"
# title = "Discrete Mathematics"

# [[sources]]
# limit = 150
# category = "cs.DC"
# title = "Distributed, Parallel, and Cluster Computing"

[[sources]]
limit = 150
category = "cs.ET"
title = "Emerging Technologies"

# [[sources]]
# limit = 150
# category = "cs.FL"
# title = "Formal Languages and Automata Theory"

# [[sources]]
# limit = 150
# category = "cs.GL"
# title = "General Literature"

[[sources]]
limit = 150
category = "cs.GR"
title = "Graphics"

# [[sources]]
# limit = 150
# category = "cs.AR"
# title = "Hardware Architecture"

[[sources]]
limit = 150
category = "cs.HC"
title = "Human-Computer Interaction"

# [[sources]]
# limit = 150
# category = "cs.IR"
# title = "Information Retrieval"

# [[sources]]
# limit = 150
# category = "cs.IT"
# title = "Information Theory"

# [[sources]]
# limit = 150
# category = "cs.LO"
# title = "Logic in Computer Science"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

# [[sources]]
# limit = 150
# category = "cs.MS"
# title = "Mathematical Software"

[[sources]]
limit = 150
category = "cs.MA"
title = "Multiagent Systems"

[[sources]]
limit = 150
category = "cs.MM"
title = "Multimedia"

# [[sources]]
# limit = 150
# category = "cs.NI"
# title = "Networking and Internet Architecture"

# [[sources]]
# limit = 150
# category = "cs.NE"
# title = "Neural and Evolutionary Computing"

# [[sources]]
# limit = 150
# category = "cs.NA"
# title = "Numerical Analysis"

# [[sources]]
# limit = 150
# category = "cs.OS"
# title = "Operating Systems"

[[sources]]
limit = 150
category = "cs.OH"
title = "Other Computer Science"

# [[sources]]
# limit = 150
# category = "cs.PF"
# title = "Performance"

# [[sources]]
# limit = 150
# category = "cs.PL"
# title = "Programming Languages"

[[sources]]
limit = 150
category = "cs.RO"
title = "Robotics"

# [[sources]]
# limit = 150
# category = "cs.SI"
# title = "Social and Information Networks"

# [[sources]]
# limit = 150
# category = "cs.SE"
# title = "Software Engineering"

# [[sources]]
# limit = 150
# category = "cs.SD"
# title = "Sound"

# [[sources]]
# limit = 150
# category = "cs.SC"
# title = "Symbolic Computation"

# [[sources]]
# limit = 150
# category = "cs.SY"
# title = "Systems and Control"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
